version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:16-browsers
    steps:
      - checkout
      - run: npm install
      - run: npm test
  on_fail:
    when: on_fail
    do:
      - echo "Tests failed, stopping workflow"

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - on_fail:
          requires:
            - build
